name: Rust

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          components: llvm-tools-preview

      - name: Add llvm-tools to PATH
        run: echo "${HOME}/.rustup/toolchains/$(rustup show active-toolchain | cut -d' ' -f1)/bin" >> $GITHUB_PATH

      - name: Install grcov
        run: cargo install grcov

      - name: Clean Build Artifacts
        run: cargo clean

      - name: Run tests with coverage
        env:
          CARGO_INCREMENTAL: "0"
          RUSTFLAGS: "-C instrument-coverage -C codegen-units=1 -C debuginfo=0"
          LLVM_PROFILE_FILE: "coverage-%p-%m.profraw"
        run: |
          cargo test --all --verbose

      - name: Generate coverage report
        run: |
          grcov . \
            --binary-path ./target/debug/ \
            -s . \
            -t lcov \
            --branch \
            --ignore-not-existing \
            --llvm \
            -o lcov.info

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          files: lcov.info
          fail_ci_if_error: true
          verbose: true
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
